COUNTRY_ABBREV = {
    # A
    "AF": "Afghanistan",
    "AFG": "Afghanistan",
    "AL": "Albania",
    "ALB": "Albania",
    "DZ": "Algeria",
    "DZA": "Algeria",
    "AD": "Andorra",
    "AND": "Andorra",
    "AO": "Angola",
    "AGO": "Angola",
    "AG": "Antigua and Barbuda",
    "ATG": "Antigua and Barbuda",
    "AR": "Argentina",
    "ARG": "Argentina",
    "AM": "Armenia",
    "ARM": "Armenia",
    "AU": "Australia",
    "AUS": "Australia",
    "AT": "Austria",
    "AUT": "Austria",
    "AZ": "Azerbaijan",
    "AZE": "Azerbaijan",
    # B
    "BS": "Bahamas",
    "BHS": "Bahamas",
    "BH": "Bahrain",
    "BHR": "Bahrain",
    "BD": "Bangladesh",
    "BGD": "Bangladesh",
    "BB": "Barbados",
    "BRB": "Barbados",
    "BY": "Belarus",
    "BLR": "Belarus",
    "BE": "Belgium",
    "BEL": "Belgium",
    "BZ": "Belize",
    "BLZ": "Belize",
    "BJ": "Benin",
    "BEN": "Benin",
    "BT": "Bhutan",
    "BTN": "Bhutan",
    "BO": "Bolivia",
    "BOL": "Bolivia",
    "BA": "Bosnia and Herzegovina",
    "BIH": "Bosnia and Herzegovina",
    "BW": "Botswana",
    "BWA": "Botswana",
    "BR": "Brazil",
    "BRA": "Brazil",
    "BN": "Brunei",
    "BRN": "Brunei",
    "BG": "Bulgaria",
    "BGR": "Bulgaria",
    "BF": "Burkina Faso",
    "BFA": "Burkina Faso",
    "BI": "Burundi",
    "BDI": "Burundi",
    # C
    "CV": "Cape Verde",
    "CPV": "Cape Verde",
    "KH": "Cambodia",
    "KHM": "Cambodia",
    "CM": "Cameroon",
    "CMR": "Cameroon",
    "CA": "Canada",
    "CAN": "Canada",
    "CF": "Central African Republic",
    "CAF": "Central African Republic",
    "TD": "Chad",
    "TCD": "Chad",
    "CL": "Chile",
    "CHL": "Chile",
    "CN": "China",
    "CHN": "China",
    "CO": "Colombia",
    "COL": "Colombia",
    "KM": "Comoros",
    "COM": "Comoros",
    "CG": "Congo",
    "COG": "Congo",
    "CD": "Democratic Republic of the Congo",
    "COD": "Democratic Republic of the Congo",
    "CR": "Costa Rica",
    "CRI": "Costa Rica",
    "HR": "Croatia",
    "HRV": "Croatia",
    "CU": "Cuba",
    "CUB": "Cuba",
    "CY": "Cyprus",
    "CYP": "Cyprus",
    "CZ": "Czech Republic",
    "CZE": "Czech Republic",
    "CZECHIA": "Czech Republic",
    # D
    "DK": "Denmark",
    "DNK": "Denmark",
    "DJ": "Djibouti",
    "DJI": "Djibouti",
    "DM": "Dominica",
    "DMA": "Dominica",
    "DO": "Dominican Republic",
    "DOM": "Dominican Republic",
    # E
    "EC": "Ecuador",
    "ECU": "Ecuador",
    "EG": "Egypt",
    "EGY": "Egypt",
    "SV": "El Salvador",
    "SLV": "El Salvador",
    "GQ": "Equatorial Guinea",
    "GNQ": "Equatorial Guinea",
    "ER": "Eritrea",
    "ERI": "Eritrea",
    "EE": "Estonia",
    "EST": "Estonia",
    "SZ": "Eswatini",
    "SWZ": "Eswatini",
    "SWAZILAND": "Eswatini",
    "ET": "Ethiopia",
    "ETH": "Ethiopia",
    # F
    "FJ": "Fiji",
    "FJI": "Fiji",
    "FI": "Finland",
    "FIN": "Finland",
    "FR": "France",
    "FRA": "France",
    # G
    "GA": "Gabon",
    "GAB": "Gabon",
    "GM": "Gambia",
    "GMB": "Gambia",
    "GE": "Georgia",
    "GEO": "Georgia",
    "DE": "Germany",
    "DEU": "Germany",
    "GH": "Ghana",
    "GHA": "Ghana",
    "GR": "Greece",
    "GRC": "Greece",
    "GD": "Grenada",
    "GRD": "Grenada",
    "GT": "Guatemala",
    "GTM": "Guatemala",
    "GN": "Guinea",
    "GIN": "Guinea",
    "GW": "Guinea-Bissau",
    "GNB": "Guinea-Bissau",
    "GY": "Guyana",
    "GUY": "Guyana",
    # H
    "HT": "Haiti",
    "HTI": "Haiti",
    "HN": "Honduras",
    "HND": "Honduras",
    "HU": "Hungary",
    "HUN": "Hungary",
    # I
    "IS": "Iceland",
    "ISL": "Iceland",
    "IN": "India",
    "IND": "India",
    "ID": "Indonesia",
    "IDN": "Indonesia",
    "IR": "Iran",
    "IRN": "Iran",
    "IQ": "Iraq",
    "IRQ": "Iraq",
    "IE": "Ireland",
    "IRL": "Ireland",
    "IL": "Israel",
    "ISR": "Israel",
    "IT": "Italy",
    "ITA": "Italy",
    # J
    "JM": "Jamaica",
    "JAM": "Jamaica",
    "JP": "Japan",
    "JPN": "Japan",
    "JO": "Jordan",
    "JOR": "Jordan",
    # K
    "KZ": "Kazakhstan",
    "KAZ": "Kazakhstan",
    "KE": "Kenya",
    "KEN": "Kenya",
    "KI": "Kiribati",
    "KIR": "Kiribati",
    "KW": "Kuwait",
    "KWT": "Kuwait",
    "KG": "Kyrgyzstan",
    "KGZ": "Kyrgyzstan",
    # L
    "LA": "Laos",
    "LAO": "Laos",
    "LV": "Latvia",
    "LVA": "Latvia",
    "LB": "Lebanon",
    "LBN": "Lebanon",
    "LS": "Lesotho",
    "LSO": "Lesotho",
    "LR": "Liberia",
    "LBR": "Liberia",
    "LY": "Libya",
    "LBY": "Libya",
    "LI": "Liechtenstein",
    "LIE": "Liechtenstein",
    "LT": "Lithuania",
    "LTU": "Lithuania",
    "LU": "Luxembourg",
    "LUX": "Luxembourg",
    # M
    "MG": "Madagascar",
    "MDG": "Madagascar",
    "MW": "Malawi",
    "MWI": "Malawi",
    "MY": "Malaysia",
    "MYS": "Malaysia",
    "MV": "Maldives",
    "MDV": "Maldives",
    "ML": "Mali",
    "MLI": "Mali",
    "MT": "Malta",
    "MLT": "Malta",
    "MH": "Marshall Islands",
    "MHL": "Marshall Islands",
    "MR": "Mauritania",
    "MRT": "Mauritania",
    "MU": "Mauritius",
    "MUS": "Mauritius",
    "MX": "Mexico",
    "MEX": "Mexico",
    "FM": "Micronesia",
    "FSM": "Micronesia",
    "MD": "Moldova",
    "MDA": "Moldova",
    "MC": "Monaco",
    "MCO": "Monaco",
    "MN": "Mongolia",
    "MNG": "Mongolia",
    "ME": "Montenegro",
    "MNE": "Montenegro",
    "MA": "Morocco",
    "MAR": "Morocco",
    "MZ": "Mozambique",
    "MOZ": "Mozambique",
    "MM": "Myanmar",
    "MMR": "Myanmar",
    "BURMA": "Myanmar",
    # N
    "NA": "Namibia",
    "NAM": "Namibia",
    "NR": "Nauru",
    "NRU": "Nauru",
    "NP": "Nepal",
    "NPL": "Nepal",
    "NL": "Netherlands",
    "NLD": "Netherlands",
    "HOLLAND": "Netherlands",
    "NZ": "New Zealand",
    "NZL": "New Zealand",
    "NI": "Nicaragua",
    "NIC": "Nicaragua",
    "NE": "Niger",
    "NER": "Niger",
    "NG": "Nigeria",
    "NGA": "Nigeria",
    "KP": "North Korea",
    "PRK": "North Korea",
    "MK": "North Macedonia",
    "MKD": "North Macedonia",
    "NO": "Norway",
    "NOR": "Norway",
    # O
    "OM": "Oman",
    "OMN": "Oman",
    # P
    "PK": "Pakistan",
    "PAK": "Pakistan",
    "PW": "Palau",
    "PLW": "Palau",
    "PA": "Panama",
    "PAN": "Panama",
    "PG": "Papua New Guinea",
    "PNG": "Papua New Guinea",
    "PY": "Paraguay",
    "PRY": "Paraguay",
    "PE": "Peru",
    "PER": "Peru",
    "PH": "Philippines",
    "PHL": "Philippines",
    "PL": "Poland",
    "POL": "Poland",
    "PT": "Portugal",
    "PRT": "Portugal",
    # Q
    "QA": "Qatar",
    "QAT": "Qatar",
    # R
    "RO": "Romania",
    "ROU": "Romania",
    "RU": "Russia",
    "RUS": "Russia",
    "RUSSIA": "Russia",
    "RW": "Rwanda",
    "RWA": "Rwanda",
    # S
    "KN": "Saint Kitts and Nevis",
    "KNA": "Saint Kitts and Nevis",
    "LC": "Saint Lucia",
    "LCA": "Saint Lucia",
    "VC": "Saint Vincent and the Grenadines",
    "VCT": "Saint Vincent and the Grenadines",
    "WS": "Samoa",
    "WSM": "Samoa",
    "SM": "San Marino",
    "SMR": "San Marino",
    "ST": "Sao Tome and Principe",
    "STP": "Sao Tome and Principe",
    "SA": "Saudi Arabia",
    "SAU": "Saudi Arabia",
    "SN": "Senegal",
    "SEN": "Senegal",
    "RS": "Serbia",
    "SRB": "Serbia",
    "SC": "Seychelles",
    "SYC": "Seychelles",
    "SL": "Sierra Leone",
    "SLE": "Sierra Leone",
    "SG": "Singapore",
    "SGP": "Singapore",
    "SK": "Slovakia",
    "SVK": "Slovakia",
    "SI": "Slovenia",
    "SVN": "Slovenia",
    "SB": "Solomon Islands",
    "SLB": "Solomon Islands",
    "SO": "Somalia",
    "SOM": "Somalia",
    "ZA": "South Africa",
    "ZAF": "South Africa",
    "KR": "South Korea",
    "KOR": "South Korea",
    "SS": "South Sudan",
    "SSD": "South Sudan",
    "ES": "Spain",
    "ESP": "Spain",
    "LK": "Sri Lanka",
    "LKA": "Sri Lanka",
    "SD": "Sudan",
    "SDN": "Sudan",
    "SR": "Suriname",
    "SUR": "Suriname",
    "SE": "Sweden",
    "SWE": "Sweden",
    "CH": "Switzerland",
    "CHE": "Switzerland",
    "SY": "Syria",
    "SYR": "Syria",
    # T
    "TW": "Taiwan",
    "TWN": "Taiwan",
    "TJ": "Tajikistan",
    "TJK": "Tajikistan",
    "TZ": "Tanzania",
    "TZA": "Tanzania",
    "TH": "Thailand",
    "THA": "Thailand",
    "TL": "Timor-Leste",
    "TLS": "Timor-Leste",
    "EAST TIMOR": "Timor-Leste",
    "TG": "Togo",
    "TGO": "Togo",
    "TO": "Tonga",
    "TON": "Tonga",
    "TT": "Trinidad and Tobago",
    "TTO": "Trinidad and Tobago",
    "TN": "Tunisia",
    "TUN": "Tunisia",
    "TR": "Turkey",
    "TUR": "Turkey",
    "TURKIYE": "Turkey",
    "TM": "Turkmenistan",
    "TKM": "Turkmenistan",
    "TV": "Tuvalu",
    "TUV": "Tuvalu",
    # U
    "UG": "Uganda",
    "UGA": "Uganda",
    "UA": "Ukraine",
    "UKR": "Ukraine",
    "AE": "United Arab Emirates",
    "ARE": "United Arab Emirates",
    "UAE": "United Arab Emirates",
    "GB": "United Kingdom",
    "GBR": "United Kingdom",
    "UK": "United Kingdom",
    "US": "United States",
    "USA": "United States",
    "UY": "Uruguay",
    "URY": "Uruguay",
    "UZ": "Uzbekistan",
    "UZB": "Uzbekistan",
    # V
    "VU": "Vanuatu",
    "VUT": "Vanuatu",
    "VE": "Venezuela",
    "VEN": "Venezuela",
    "VN": "Vietnam",
    "VNM": "Vietnam",
    # Y
    "YE": "Yemen",
    "YEM": "Yemen",
    # Z
    "ZM": "Zambia",
    "ZMB": "Zambia",
    "ZW": "Zimbabwe",
    "ZWE": "Zimbabwe",
}